# site settings
title: Cole Johnson
subtitle: 
email: colejohnson451@gmail.com
description: Computer Science Student at USC<br/>Machine Learning & Software Development
baseurl: "" 
url: "https://cjohnson451.github.io" 
author:
street_address: 1177 W 29th St
city: Los Angeles
state: CA
zip_code: 90007
country: United States of America
phone: 301-980-7655

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/cjohnson451
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: www.linkedin.com/in/cole-johnson-758394278  
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
